const scenarios={normal:{health:'98%',healthNote:'All services nominal',alerts:'0',alertNote:'No action required',confidence:'96%',title:'No anomaly detected',copy:'Sensor behaviour remains within the expected operating envelope.',recommendation:'Continue monitoring.',badge:'Nominal',cls:'nominal',line:'0,155 70,145 140,150 210,130 280,138 350,118 420,125 490,112 560,120 630,100 700,108'},warning:{health:'84%',healthNote:'1 subsystem degraded',alerts:'1',alertNote:'Review recommended',confidence:'87%',title:'Thermal deviation detected',copy:'Sensor T-04 is trending above its expected operating envelope.',recommendation:'Inspect thermal subsystem within 15 minutes.',badge:'Warning',cls:'warning',line:'0,160 70,150 140,147 210,138 280,130 350,119 420,103 490,88 560,69 630,51 700,39'},critical:{health:'61%',healthNote:'Immediate attention required',alerts:'1',alertNote:'Critical response',confidence:'94%',title:'Critical thermal anomaly',copy:'A rapid sustained increase indicates a high-risk deviation from the baseline.',recommendation:'Escalate to supervisor and isolate subsystem.',badge:'Critical',cls:'critical',line:'0,165 70,157 140,148 210,143 280,132 350,112 420,91 490,68 560,43 630,25 700,12'}};
let current='normal';const $=s=>document.querySelector(s);const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function addLog(kind,title,detail){const row=document.createElement('div');row.className='log-row';row.innerHTML=`<time>${now()}</time><span class="dot ${kind}"></span><strong>${title}</strong><p>${detail}</p>`;$('#log').prepend(row)}
function setScenario(name){current=name;const s=scenarios[name];document.querySelectorAll('.scenario').forEach(b=>b.classList.toggle('active',b.dataset.scenario===name));$('#health').textContent=s.health;$('#health-note').textContent=s.healthNote;$('#alerts').textContent=s.alerts;$('#alert-count').textContent=s.alerts;$('#alert-note').textContent=s.alertNote;$('#confidence').textContent=s.confidence;$('#ai-confidence').textContent=s.confidence;$('#confidence-fill').style.width=s.confidence;$('#ai-title').textContent=s.title;$('#ai-copy').textContent=s.copy;$('#recommendation').textContent=s.recommendation;$('#signal-badge').textContent=s.badge;$('#signal-badge').className=`badge ${s.cls}`;$('#signal-line').setAttribute('points',s.line);$('#review-btn').disabled=name==='normal';$('#ai-card').className='ai-card'+(name==='warning'?' warning-state':name==='critical'?' critical-state':'');$('#response').textContent=name==='normal'?'Ready':'Pending';$('#response-note').textContent=name==='normal'?'Awaiting events':'Operator review required';if(name!=='normal')addLog(s.cls,`${s.badge} alert generated`,s.title)}
document.querySelectorAll('.scenario').forEach(b=>b.addEventListener('click',()=>setScenario(b.dataset.scenario)));
$('#review-btn').addEventListener('click',()=>{const s=scenarios[current];$('#modal-severity').textContent=s.badge.toUpperCase();$('#modal-title').textContent=s.title;$('#modal-detail').textContent=s.copy;$('#modal-confidence').textContent=s.confidence;$('#modal-recommendation').textContent=s.recommendation;$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false')});
function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true')}
$('#close-modal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;const note=$('#operator-note').value.trim();const labels={dismiss:'Alert dismissed',acknowledge:'Alert acknowledged',escalate:'Alert escalated'};addLog(action==='escalate'?'critical':'ok',labels[action],note||`Operator selected ${action}.`);$('#response').textContent=action==='escalate'?'Escalated':action==='acknowledge'?'Acknowledged':'Dismissed';$('#response-note').textContent='Audit trail updated';closeModal()}));
$('#reset-log').addEventListener('click',()=>{$('#log').innerHTML='<div class="log-row"><time>'+now()+'</time><span class="dot ok"></span><strong>Audit trail reset</strong><p>Simulation returned to baseline.</p></div>';setScenario('normal')});